### ISSUE TITLE
Issue with aws-actions/configure-aws-credentials@v1 - GLIBC_2.28' not found

### ISSUE THREAD

**Issue by karty-s** [aws-actions/configure-aws-credentials#1106]
### Describe the bug

HI Team, our github actions workflows which uses the configure aws actions V1 started failing with the below error from past two days :-
```
Run aws-actions/configure-aws-credentials@v1
/opt/actions-runner/externals/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /opt/actions-runner/externals/node20/bin/node)
/opt/actions-runner/externals/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /opt/actions-runner/externals/node20/bin/node)
```

we tried using the V3 and V4 as well but no luck, kindly provide a fix for this.
runner os - amazon linux 2

### Expected Behavior

The action should be able to fetch the glib 2.26 available with node20 AL2 , or use the node16 available with the runner instance

### Current Behavior

currently the action picks up node20 which supports glib2.28 which is available in AL 2 +

### Reproduction Steps

os version - Amazon linux 2
node version - node 20 
action - Run aws-actions/configure-aws-credentials@v1
 error :- 
/opt/actions-runner/externals/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /opt/actions-runner/externals/node20/bin/node)
/opt/actions-runner/externals/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /opt/actions-runner/externals/node20/bin/node)

**Comment by Bubbassauro** [comment]
As a workaround to fix our GA, we had to add this to the workflow level, according to this discussion:
https://github.com/actions/checkout/issues/1809#issuecomment-2208202462

```yaml
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
```

and reverted to using:
```yaml
uses: aws-actions/configure-aws-credentials@v1-node16
```

**Comment by tim-finnigan** [comment]
Thanks for reaching out, other workarounds were referenced here as well: https://github.com/aws-actions/configure-aws-credentials/issues/862. AL2 uses `glibc` 2.26 per https://docs.aws.amazon.com/linux/al2023/ug/glibc-gcc-and-binutils.html. I'm able to run `v4` on `ubuntu-latest` (Ubuntu 22.04.4 LTS) with Node 18.

**Comment by kellertk** [comment]
This is a known issue for Node runtimes on Amazon Linux 2. The problem is that your node runtime has been compiled against a newer version of glibc than is available on the system. In order to continue to use Node 20, on AL2 with this action, you'll need to provide/compile your own Node runtime against glibc 2.26. See https://repost.aws/questions/QUvkkhY--uTiSDkS6R1jFnZQ/node-js-18-on-amazon-linux-2 for an example.

This action doesn't have any control over which node runtime is available on your system, other than the using directive in the action.yml file. Another option is to migrate to AL 2023, which uses much more up to date libraries.
