### ISSUE TITLE
Add AWS_SESSION_TOKEN example back to README

### ISSUE THREAD

**Issue by humphd** [aws-actions/configure-aws-credentials#311]
I had to use `aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}` today in order to authenticate successfully, and I only discovered it via this old commit 3042b009625a34bedaba3cc28b2713a8e11d4f2b.  It looks like it got removed in https://github.com/aws-actions/configure-aws-credentials/commit/b8c74de753fbcb4868bf2011fb2e15826ce973af#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L30, possibly by mistake?

I think it's pretty useful to include it, and I'd suggest adding it back.

**Comment by NathanielRN** [comment]
This is probably related to #302 , because the code to make it work with OIDC is merged as you pointed out in https://github.com/aws-actions/configure-aws-credentials/commit/b8c74de753fbcb4868bf2011fb2e15826ce973af#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L30 but the release for it has not been made yet.

**Comment by peterwoodworth** [comment]
There's now an example of this in the docs
