### ISSUE TITLE
Retry mechanism for 403 errors agaist Github ID Token API

### ISSUE THREAD

**Issue by jkroepke** [aws-actions/configure-aws-credentials#469]
If concurrency groups are enabled for tasks, jobs are getting in Pending state.

Since the `aws-actions/configure-aws-credentials` is one of the first actions, the action would instantly tries to call the Github ID Token Endpoint.

Sometimes, the Github API raises an error like

```
Error: Error message: Failed to get ID Token. 
        Error Code : 403
        Error Message: Can't issue ID_TOKEN for job in 'Pending' state.
```
which is not true.

It seems like a race condition on GitHub site. Retrying the request in 1 or 2 seconds would resolve this error until the error is fixed on GitHub site.

**Comment by neptune19821220** [comment]
We met the same issue.
We use matrix to create multiple similar jobs.
The job failed occasionally and got a error msg.
Error Message: Can't issue ID_TOKEN for job in 'Delayed' state.

**Comment by adamnoll** [comment]
Same issue here. We are occasionally getting this error as well.

**Comment by nsheaps** [comment]
We also get this from time to time in our CI workflows. Amazon AWS Support suggested retrying, but I would love to know if that retry mechanism could be built into the action itself until github addresses the instability on their side, since retrying at the workflow/job level is unnecessarily and increases costs.

**Comment by peterwoodworth** [comment]
`v3` should now retry when the github token creation fails
