### ISSUE TITLE
Support tagged releases of the node16 variant

### ISSUE THREAD

**Issue by marcofranssen** [aws-actions/configure-aws-credentials#632]
### Describe the feature

Currently we have no decent way to pin to a certain release of the node16 variant.

Dependabot will also try to bump our node16 variant to the non node16 variant.

### Use Case

Have proper release management of this GitHub action to support dependabot and allow consumers to do version pinning.

### Proposed Solution

Have tagged releases of the node16 variant (maybe 2.x.x) releases.

### Other Information

This is what dependabot sees as a new version.

```diff
- uses: aws-actions/configure-aws-credentials@v1-node16
+ uses: aws-actions/configure-aws-credentials@v1.7.0
```

However that means we are downgrading again to node12, which will reintroduce all those deprecation notices.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sefasenturk95** [comment]
See https://github.com/aws-actions/configure-aws-credentials/issues/489#issuecomment-1278145876 on how to solve this.

**Comment by ccolella-mdc** [comment]
This seems like the obvious solution. It would be so easy to update to node 16 for a v2 release and then change their current plans for a v2 to be called v3 instead.

**Comment by zyv** [comment]
Unfortunately, the conversation in aws-actions/configure-aws-credentials#489 was locked, so I'm linking these issues this way. Anyways, more than half a year later, v2 is still not released and the situation with `v1-node16` tag is not really tenable for the reasons described here.

I also think that just releasing v2 and keeping "next big things" for v3 (if they aren't ready yet) would be the way to go /cc @peterwoodworth @kellertk

**Comment by marcofranssen** [comment]
Could this be speed up a bit?

```shell
Run aws-actions/configure-aws-credentials@v1-node16
(node:3226) NOTE: The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
```

Now we also get deprecation warnings the current version won't be supported this year.

**Comment by kellertk** [comment]
@marcofranssen That deprecation is the major reason we're developing the v2 of this action. We're on the same team as the JS SDK team, so we knew this was coming and are mostly done with the first pass of moving everything to the v3 SDK. I know it's been some time since we've given you an update on this dev work, but some of it was deprioritized for other issues. Expect a status update around this by the end of next week.

Also, I can confirm we're going to implement this. It's obvious that there's a need for it for the reason you stated above and because stable tagging is required to avoid #670. Expect updates soon.
