### ISSUE TITLE
Consider lowering the role-duration default to 1 hour for role chaining

### ISSUE THREAD

**Issue by j3parker** [aws-actions/configure-aws-credentials#79]
Currently the default for `role-duration` default is 6 hours: https://github.com/aws-actions/configure-aws-credentials/blob/da082bd93714de23a05548c70272c22b02c13ede/action.yml#L37-L39

documented here:

https://github.com/aws-actions/configure-aws-credentials/blob/da082bd93714de23a05548c70272c22b02c13ede/README.md#L83

The rationale behind this is described in the code here:

https://github.com/aws-actions/configure-aws-credentials/blob/da082bd93714de23a05548c70272c22b02c13ede/index.js#L5-L7

That's a sensible default. I'd like to propose lowering the default to one hour to make the experience nicer for role-chaining. See [the footnote on this page]:

> Using the credentials for one role to assume a different role is called role chaining. When you use role chaining, your new credentials are limited to a maximum duration of one hour. When you use roles to grant permissions to applications that run on EC2 instances, those applications are not subject to this limitation.

How does this come up for us? We have an automation that rotates IAM tokens in our GitHub repos. It uses temporary role tokens (with a 12 hour lifetime, rotated every 6 hours). For repos that need multiple roles we generate a "hub role" restricted to assuming that repos different roles (with an explicit deny for everything else). We install tokens for this "hub role" into the repos secrets. The error message that happens is easy to understand:

```
##[error]The requested DurationSeconds exceeds the 1 hour session limit for roles assumed by role chaining.
```

If we could pick a default from the start, I think 1 hour would make a bit more sense, just so that this case was smooth. I think it's not a very niche case but I'm not sure. One hour is still a reasonably long time for a build, and setting `role-session-duration` to 6 hours explicitly would still work.

If you're uncomfortable lowering the default, I understand. If you want a PR I'd be happy to do that.

At the very least, posting this so it shows up if someone searches for the error.

**Comment by pkandasamy91** [comment]
@j3parker Thanks for the detailed description, we really appreciate it! I definitely understand why it might makes sense to reduce the default session limit to 1 hour. However, since you can override the default using the role-session-duration flag and this would be a backwards breaking change, we're not in favour (at this time) of reducing the default session limit. Anyone who's currently using the default session limit to perform an action might be expecting the current default of 6 hours, and by changing this behaviour to 1 hour, we could be negatively impacting users in which a previously working workflow might start to fail.

**Comment by j3parker** [comment]
Nope, sounds good to me!
