### ISSUE TITLE
Action fails when GITHUB_REF does not exist

### ISSUE THREAD

**Issue by billputer** [aws-actions/configure-aws-credentials#80]
Certain workflows don't set a GITHUB_REF variable, because the triggering event doesn't have a branch or tag. See [GitHub's docs on GITHUB_REF](https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables). 

However, this action [fails with an error](https://github.com/aws-actions/configure-aws-credentials/blob/472e549195ba1f153e9fb72e39dc2a094e5de13e/index.js#L33) when the GITHUB_REF environment variable doesn't exist, with the output `##[error]Missing required environment value. Are you running in GitHub Actions?`.

**Comment by sergirosell** [comment]
We are facing an issue related with this as since the update v2.272.0 our self-hosted runners seems to have empty the variable GITHUB_ACTION and as is enforced on the code that must be defined this is causing us to not be able to assume-role and run our pipelines.

As this variables are just for sts:TagSession maybe should be interesting to have it as optional not required. As explained on the previos note, we encounter the error ##[error]Missing required environment value. Are you running in GitHub Actions?.

We have also opened an issue to GitHub but until they solve it we are blocked.
https://github.com/actions/runner/issues/635

**Comment by bennettl** [comment]
This is breaking all our pipelines, even if we set `role-skip-session-tagging: true` its checking for the github env vars which are not set

**Comment by allisaurus** [comment]
Thanks for reporting @sergirosell & @bennettl - sounds like the issue with the runner [was rolled back](https://github.com/actions/runner/issues/635#issuecomment-668628287), but we're working on fixing this for `GITHUB_REF` and the other env vars when tagging is skipped.

**Comment by allisaurus** [comment]
FYI we are tracking issues with remaining env vars here: https://github.com/aws-actions/configure-aws-credentials/issues/105
